### ISSUE TITLE
the codes of Figure A1: Failure Visualization and Figure A2: T-SNE

### ISSUE THREAD

**Issue by dana-niu** [CHENGY12/PLOT#10]
hello
Can you provide some codes of Figure A1: Failure Visualization and Figure A2: T-SNE?
I would appreciate it if you could provide it for study.

**Comment by CHENGY12** [comment]
Hi, thanks for your attention.

For Failure Visualization, you can refer to our code here [Visualization](https://github.com/CHENGY12/PLOT/blob/main/visualization.py).  The image examples can be found in the StanfordCars dataset.

For the T-SNE, you can use the package sklearn.

**Comment by dana-niu** [comment]
Your reply was very helpful.
Thank you very much for your reply.

**Comment by dana-niu** [comment]
hello
I see the code you provided.
I have another question. There are two data in your code as follows.
transport_plans = torch.load('path_of_plan') # transport_plans shape=[N,d,d], e.g. [4,7,7]
original_image = torch.load('path_of_image') # original_image shape=[1,3,224,224]

How was the first transport_plans data obtained?
Could you be more specific?
Thank you very much.

**Comment by CHENGY12** [comment]
PLOT, our method, is to learn transport_plans to do optimal transport between multiple prompts and local features. It is learned by the Sinkhorn algorithm.  Please refer to our paper and this repo for details. You can also download our model parameters.
