### ISSUE TITLE
请教一下visualization问题

### ISSUE THREAD

**Issue by sjkjsandy** [CHENGY12/PLOT#12]
您好，请教一下visualization中 transport_plans   shape=[N,d,d]，这个数据是怎么生成的？为什么是 [4,7,7]？  4是4个 number of text prompts，7是什么呢？  是指需要7*7=49个number of vision prompts吗？

**Comment by CHENGY12** [comment]
Hi, @sjkjsandy, 7x7=49 is about the number of local visual features in the feature map.

**Comment by sjkjsandy** [comment]
Thank you very much for your patient guidance!
