### ISSUE TITLE
Questions about visualization of transport plan

### ISSUE THREAD

**Issue by tomchen-ctj** [CHENGY12/PLOT#4]
Hi, 

Thank you for sharing your great work.

May I ask more about the details of the visualization of transport plan T? 

Thank you.

**Comment by CHENGY12** [comment]
Hi, thanks very much for your attention to our work.  We included a brief introduction [here](https://github.com/CHENGY12/PLOT/tree/main/plot-coop#visualization).  In light of your suggestion, we will add an extra script for visualization very soon!

**Comment by tomchen-ctj** [comment]
Thank you!
