### ISSUE TITLE
Question about the number of runs used

### ISSUE THREAD

**Issue by ybendou** [CHENGY12/PLOT#5]
Hi, 

Thank you for the very nice repo and congrats for your paper being accepted at ICLR 2023!
I have a question regarding the number of runs you use to generate your results as it is not very clear even in the CoOp paper which you base your experiments on. How many few-shot evaluation runs are used per datapoint?

Thanks in advance!

**Comment by CHENGY12** [comment]
Hi,

Thanks for your attention to our method.  In the few-shot setting, we follow the protocol in CoOp which runs the experiments three times with seed=1,2,3 for 1,2,4,8,16-shots. Please refer to the [scripts](https://github.com/CHENGY12/PLOT/blob/main/plot-coop/scripts/main.sh#L19) (running file) for the details.  
Hope it can help.  Please don't hesitate to let me know if you still have questions.

**Comment by ybendou** [comment]
Thank you! That's helpful! 
The same seed might generate different results on different machines. I will run your code and check if I get the same result with the same seed. 
Best regards,
