### ISSUE TITLE
Some confusion about the local features and global feature in the ViT backbone.

### ISSUE THREAD

**Issue by jingzhengli** [CHENGY12/PLOT#8]
To my knowledge, the output of VisionTransformer is a embeding of class token head, 
```
        x = self.ln_post(x[:, 0, :])
        if self.proj is not None:
            x = x @ self.proj
```

In plotpp.py:
```
        image_features = self.image_encoder(image.type(self.dtype), vision_prompts)
        image_feature_pool = image_features.mean(dim=0)
```
Thus, **I think the "image_features" don't contain global and local features.** Could you help me to understand this case? Thanks

**Comment by CHENGY12** [comment]
Hi jingzheng,  the PLOT++ is a bit different.  We found that the local features of ViT are not as discriminative as the ones of ResNet. So we propose to learn the local features instead. To achieve this, we fix the textual prompts and learn multiple local features with visual prompts.  You can check the [model](https://github.com/CHENGY12/PLOT/blob/main/plot-pp/clip/model.py) and [the learner](https://github.com/CHENGY12/PLOT/blob/main/plot-pp/trainers/plotpp.py#L56)
