### ISSUE TITLE
 Something Upload Wrong log file in PLOT++ 

### ISSUE THREAD

**Issue by Alienge** [CHENGY12/PLOT#9]
Thanks for your elegant works!!! 
There are mistakes in upload the weight  in caltech101?  I find to train 1 shot loading the 16 shot weight  in stage 2.  [here](https://mbzuaiac-my.sharepoint.com/personal/zhengqing_gao_mbzuai_ac_ae/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fzhengqing%5Fgao%5Fmbzuai%5Fac%5Fae%2FDocuments%2FPLOT%2DPP%20models%2FPLOT%2B%2B%5Fmodels%2Fcaltech101%2F1shots%2Fstage2%2Fseed1%2Flog%2Etxt&parent=%2Fpersonal%2Fzhengqing%5Fgao%5Fmbzuai%5Fac%5Fae%2FDocuments%2FPLOT%2DPP%20models%2FPLOT%2B%2B%5Fmodels%2Fcaltech101%2F1shots%2Fstage2%2Fseed1) 

But the performance of caltech101's 1 shot seems correct.

**Comment by hit-Chris** [comment]
Hi, thanks for your support! I have rerun our model on caltech101 dataset under 1 shot setting on a machine with 1 RTX 4090 GPU, and the performance shown in the table is also updated. You may find the latest model [here](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/zhengqing_gao_mbzuai_ac_ae/Eu3gXZ1wvcdDngL_dLfkvG4BIoygMHSFI9h3gBHoEnJdGQ?e=OY65SW).

**Comment by Alienge** [comment]
That's great!!! Thx

**Comment by Alienge** [comment]
One more questions!!!  
I find  to train the visual prompts in order to encode the visual features. But the visual prompts  generate only from seed1 step. We know the different seeds will result in different data(image) to be load(train).  If we train the text prompts of seed2 step loading the seed1 weight , the process indirectly uses the data of seed1 step when training seed2 step. This seems unfair.

**Comment by CHENGY12** [comment]
Hi, thanks for your question!  
Following the setting of Coop, we found that the dataset split is not related with seeds (so we use this). Please let us know if you find something different.

**Comment by Alienge** [comment]
Got it !!!
Glad to hear from you!
Thx!!!
